kind: ConfigMap
apiVersion: v1

metadata:
  name: raas-application-config
  namespace: aas-dev

immutable: false

data:
  application.yaml: |-
    management:
      endpoints:
        web:
          exposure:
            include: "*"
      server:
        port: 8081
